# Site settings
title: Flutter 中文文档 - Flutter 社区中文资源
# description: TBC
email: flutter-dev@googlegroups.com
url: https://flutter.cn
port: 4002
github_username: flutter
repo:
  organization: https://github.com/flutter
  this: https://github.com/cfug/flutter.cn
  flutter: https://github.com/flutter/flutter
  samples: https://github.com/flutter/samples
branch: master

dart:
  api: https://api.dart.dev
  sdk:
    channel: stable
sdk: # Flutter SDK
  channel: stable # When changing this value also update it in src/_assets/js/archive.js

social:
  twitter: https://twitter.com/flutterdev
  youtube: https://www.youtube.com/flutterdev

dart-site: https://dart.cn
news: https://news.dartlang.org
api: https://api.flutter-io.cn
master-api: https://master-api.flutter-io.cn
pub: https://pub.flutter-io.cn
pub-api: https://pub.flutter-io.cn/documentation
pub-pkg: https://pub.flutter-io.cn/packages
flutter-medium: https://medium.com/flutter
medium: https://medium.com
dartpad: https://dartpad.cn
material: https://material-io.cn
so: https://stackoverflow.com
github: https://github.com
flutter-assets: https://flutter.github.io/assets-for-api-docs/assets
android-dev: https://developer.android.google.cn
codelabs: https://codelabs.flutter-io.cn
groups: https://groups.google.com
firebase: https://firebase.google.cn
dartpadx-dart: https://dartpad.cn/experimental/embed-new-dart.html ## Adding the exp version for dart here.

defaults:
- scope:
    path: ''
  values:
    layout: default
    show-nav-get-started-button: true
    # To hide banners from every page, comment out the `show_banner` setting
    # below. To selectively enable a banner (say, on the homepage) add
    # `show_banner: true` to the page's frontmatter.
    # DON'T HIDE BANNERS! Hiding banners makes nav-tabs break.
    # DETAILS: https://github.com/flutter/website/issues/3897
    show_banner: true
    show_footer: true
- scope:
    path: 'docs'
  values:
    toc: true
- scope:
    path: 'docs/cookbook'
  values:
    show_breadcrumbs: true
- scope:
    path: 'docs/development'
  values:
    show_breadcrumbs: true
- scope:
    path: 'docs/development/ui/widgets'
  values:
    toc: false
- scope:
    path: 'docs/get-started'
  values:
    show_breadcrumbs: true
- scope:
    path: 'docs/get-started/flutter-for'
  values:
    show_breadcrumbs: false

# Build settings

assets:
  sources:
    - _shared/_assets
    - _shared/_assets/css

# kramdown: {show_warnings: true}
plugins:
  - jekyll-toc
source: src
# `symlinked-sources` can refer to individual files or directories
# under `src` that are symlinked to somewhere outside `src`, or it can
# refer to the root folder of the symlinked content (like `site-shared/src`):
symlinked-sources: [site-shared/src]
toc:
  min_level: 2
  max_level: 4

## Site-wide shorthands

os-list: [Windows, macOS, Linux]

alert:
  bonus: >-
    <aside class="alert alert-info" role="alert" markdown="1">
    **Bonus questions!**
  important: >-
    <aside class="alert alert-warning" role="alert" markdown="1">
    <i class="fas fa-exclamation-circle"></i> **重点提醒**
  info: >-
    <aside class="alert alert-info" role="alert" markdown="1">
    <i class="fas fa-info-circle"></i>
  note: >-
    <aside class="alert alert-info" role="alert" markdown="1">
    <i class="fas fa-info-circle"></i> **备忘**
  secondary: >-
    <aside class="alert alert-secondary" role="alert" markdown="1">
  tip: >-
    <aside class="alert alert-success" role="alert" markdown="1">
    <i class="far fa-lightbulb"></i> **小提示**
  warning: >-
    <aside class="alert alert-warning" role="alert" markdown="1">
    <i class="fas fa-exclamation-triangle"></i> **请注意**
  end: </aside>

custom:
  dartpad:
    embed-dart-prefix: https://dartpad.cn/embed-dart.html
    embed-flutter-prefix: https://dartpad.cn/embed-flutter.html
    embed-html-prefix: https://dartpad.cn/embed-html.html
    embed-inline-prefix: https://dartpad.cn/embed-inline.html

  # callout_danger: '<div class="bs-callout bs-callout-danger">'
  # callout_default: '<div class="bs-callout bs-callout-default">'
  # callout_primary: '<div class="bs-callout bs-callout-primary">'
  # callout_success: '<div class="bs-callout bs-callout-success">'
  # callout_info: '<div class="bs-callout bs-callout-info">'
  # callout_warning: '<div class="bs-callout bs-callout-warning">'

  # hr_faded: '<hr class="faded"/>'
  # hr_shaded: '<hr class="shaded"/>'
