name: inject_dartpad
publish_to: none

environment:
  sdk: ^3.9.0

dependencies:
  html_unescape: ^2.0.0
  web: ^1.1.0

dev_dependencies:
  build_runner: ^2.4.15
  build_web_compilers: ^4.1.5
  path: ^1.9.0
  test: ^1.25.9
  webdev: any
