name: inject_dartpad
publish_to: none

environment:
  sdk: ^3.9.0

dependencies:
  html_unescape: ^2.0.0
  web: ^1.1.1

dev_dependencies:
  build_runner: ^2.9.0
  build_web_compilers: ^4.3.0
  path: ^1.9.1
  test: ^1.26.3
  webdev: ^3.7.2
