name: translator_bot

on:
  issue_comment:
    types: [created]

jobs:
  translator-bot-job:
    runs-on: ubuntu-latest
    name: translator-bot
    if: |
      github.repository == 'cfug/flutter.cn' &&
      github.event_name == 'issue_comment' &&
      !github.event.issue.pull_request &&
      contains(fromJson('["member", "owner"]'), github.event.comment.author_association)
    steps:
      - name: run translator-bot
        uses: cfug/translator_bot@main
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          gemini_api_key: ${{ secrets.GEMINI_API_KEY }}
